@startuml

class VedioSite {
    void freeMovie();
    void vipMovie();
    void ticketMovie();
}

class FixBugVedioSite {

}

class ProxyFreeVedioSite {

}

VedioSite <|- FixBugVedioSite
VedioSite <|- ProxyFreeVedioSite
ProxyFreeVedioSite o-- FixBugVedioSite
@enduml